# Generated by Django 4.0.5 on 2022-06-15 01:18

from django.db import migrations, models
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DataPatient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('patient', models.CharField(max_length=200)),
                ('age', models.IntegerField()),
                ('neurological', models.IntegerField()),
                ('cardiovascular', models.IntegerField()),
                ('respiratory', models.IntegerField()),
                ('coagulation', models.IntegerField()),
                ('hepatic', models.IntegerField()),
                ('renal', models.IntegerField()),
                ('icc', models.IntegerField()),
                ('ecog', models.IntegerField()),
                ('classification', models.IntegerField()),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
