# Generated by Django 4.0.5 on 2022-06-22 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DataPatient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient', models.CharField(max_length=200)),
                ('age', models.IntegerField()),
                ('neurological', models.IntegerField()),
                ('MeaningNeurological', models.CharField(max_length=200)),
                ('cardiovascular', models.IntegerField()),
                ('MeaningCardiovascular', models.CharField(max_length=200)),
                ('respiratory', models.IntegerField()),
                ('MeaningRespiratory', models.CharField(max_length=200)),
                ('coagulation', models.IntegerField()),
                ('MeaningCoagulation', models.CharField(max_length=200)),
                ('hepatic', models.IntegerField()),
                ('MeaningHepatic', models.CharField(max_length=200)),
                ('renal', models.IntegerField()),
                ('MeaningRenal', models.CharField(max_length=200)),
                ('icc', models.IntegerField()),
                ('MeaningIcc', models.CharField(max_length=200)),
                ('ecog', models.IntegerField()),
                ('MeaningEcog', models.CharField(max_length=200)),
                ('scoreSOFA', models.IntegerField()),
                ('scoreFragility', models.IntegerField()),
                ('scoreTotal', models.IntegerField()),
                ('classification', models.IntegerField()),
                ('active', models.BooleanField()),
            ],
        ),
    ]
